version: '2'
services:
  asterisk_event_adapter:
    build: ./asterisk_event_adapter
    depends_on:
      - asterisk
    ports:
      - 9991:9991
      - 9992:9992
    environment:
      - PRIVATE_ADDR
      - ASTERISK_API_USER
      - ASTERISK_API_SECRET
      - SIGNALING_PROXY_HOST
      - DEBUG=meshage
    restart: on-failure
  asterisk:
    build: ./asterisk
    network_mode: host
    ports:
      - 5060:5060/udp
      - 5038:5038
      - 8088:8088
    environment:
      - INSTANCE_NAME
      - INSTANCE_TYPE
      - PRIVATE_ADDR
      - CONSUL_HOST