version: '2'
services:
  consul:
    command: -bootstrap
    image: gliderlabs/consul-server
    ports:
    - 80:80
    - 8300:8300
    - 8400:8400
    - 8500:8500
    - 8600:53/udp
  redis:
    image: redis
    ports:
    - 6379:6379
  kamailio:
    build: ./kamailio
    ports:
      - 5060:5060/udp
    depends_on:
      - consul