version: '2'
services:
  api:
    build: ./api
    ports:
      - 9999:9999
    depends_on:
      - asterisk
    environment:
      - DISABLED=false
      - ASTERISK_HOST=$PRIVATE_ADDR
      - ASTERISK_API_USER
      - ASTERISK_API_SECRET
      #- RAW_ES_CONFIG='{"type":"redis","host":"ccsip-kamailio-0.open-cc.org"}'
    restart: on-failure
  asterisk:
    build: ./asterisk
    network_mode: host
    ports:
      - 5060:5060/udp
      - 5038:5038
      - 8088:8088