version: '2'
services:
  consul:
    command: -bootstrap
    image: gliderlabs/consul-server
    ports:
    - 8300:8300
    - 8400:8400
    - 8500:8500
    - 8600:53/udp
  redis:
    image: redis
    ports:
    - 6379:6379
  twilio_event_adapter:
    build: ./twilio_event_adapter
    ports:
      - 9993:9993
      - 9994:9994
      - 9999:9999
    environment:
      - PRIVATE_ADDR
      - CLUSTER_PORT=9993
      - SERVICE_PORT=9994
      - TWILIO_SERVICE_PORT=9999
      - TWILIO_AUTH_TOKEN
      - SIGNALING_PROXY_HOST
      - DEBUG=meshage
  kamailio_event_adapter:
    build: ./kamailio_event_adapter
    ports:
      - 9991:9991
      - 9992:9992
    environment:
      - PRIVATE_ADDR
      - DEBUG=meshage
  kamailio:
    build: ./kamailio
    ports:
      - 5060:5060/udp
    depends_on:
      - consul
      - kamailio_event_adapter
    environment:
      - SIP_EXTENSION_SECRET
      - SIP_TERMINATION_PHONE_NUMBER
  api_proxy:
    build: ./api_proxy
    ports:
      - 80:80
    cap_add:
      - NET_ADMIN
    depends_on:
      - consul