version: '2'
services:
  api:
    build: ./api
    ports:
      - 9999:9999
      - 9991:9991
      - 9992:9992
    environment:
      - DISABLED=false
      - SIGNALING_PROXY_HOST
      - INSTANCE_NAME
      - INSTANCE_TYPE
      - PRIVATE_ADDR
      - CONSUL_HOST
      - SIP_EXTENSION_SECRET
      #- RAW_ES_CONFIG={"type":"redis","host":"$REDIS_HOST"}