version: '2'
services:
  api:
    build: ./api
    depends_on:
      - asterisk
    environment:
      - EXTERNAL_ADDR=asterisk
      - DISABLED=false
    restart: on-failure
  asterisk:
    build: ./asterisk
    ports:
      - 5060:5060/udp
      - 8088:8088