version: '2'
services:
  api:
    build: ./api
    ports:
      - 9999:9999
    depends_on:
      - asterisk
    environment:
      - DISABLED=true
      - ASTERISK_HOST=asterisk
      - ASTERISK_API_USER
      - ASTERISK_API_SECRET
    restart: on-failure
  asterisk:
    build: ./asterisk
    ports:
      - 5038:5038
      - 5060:5060/udp
      - 8088:8088