version: '2'
services:
  asterisk:
    image: 'dougbtv/asterisk14'
    network_mode: 'host'
    volumes:
       - './asterisk/etc/asterisk:/etc/asterisk'
    environment:
      - LOCAL_NET
      - EXTERNAL_ADDR
      - SIP_TERMINATION_PHONE_NUMBER