version: '2'
services:
  consul:
    command: -server -bootstrap
    image: progrium/consul
    ports:
    - 80:80
    - 8300:8300
    - 8400:8400
    - 8500:8500
    - 8600:53/udp
  registrator:
    hostname: registrator
    command: -internal consul://consul:8500
    image: gliderlabs/registrator:latest
    depends_on:
      - consul
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
  kamailio:
    build: ./kamailio
    ports:
      - 5060:5060/udp
    depends_on:
      - consul
    environment:
      - EXTERNAL_ADDR
  asterisk:
    build: ./asterisk
    ports:
      - 8088:8088
      - 10001:10001/udp
    environment:
      - SERVICE_NAME=asterisk
      - LOCAL_NET
      - EXTERNAL_ADDR
      - SIP_TERMINATION_PHONE_NUMBER
